name: My first CI/CD pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download repository
      uses: actions/checkout@v2

    - name: Install JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload package .jar to deploy later
      uses: actions/upload-artifact@v4
      with:
        name: moviecards-java
        path: "${{ github.workspace }}/target/*.jar"

  test:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install Chrome and ChromeDriver for end to end tests
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt --fix-broken install -y 
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -L -o chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Run the application for end-to-end testing
        run: mvn spring-boot:run & sleep 60

      - name: Run the unit, integration, and end-to-end tests
        run: mvn clean verify

  qa:
    needs: test
    runs-on: self-hosted
    continue-on-error: true
    steps:
    - name: Download repository
      uses: actions/checkout@v2

    - name: Instalar JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: "11"
        distribution: "temurin"
        architecture: "aarch64"

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Review code quality with Sonarqube
      run: |
        mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=admin1

  stage:
    runs-on: ubuntu-latest
    needs: qa
    if: github.ref=='refs/heads/main'
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: moviecards-java

      - name: Deploy to Azure Web App (Staging)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moviecards-pre-villar'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_12F11B88D8CE4CA7B28172DF9308BA56 }}

  deploy:
    runs-on: ubuntu-latest
    needs: stage
    if: github.ref=='refs/heads/main'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TOKEN }}
          approvers: adrianavillar

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: moviecards-java
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moviecards-villar'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D09E7F855A2844D7909ACD104905814F }}