name: Mi priemra integraci칩n continua

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: empaquetado
      run: echo "Empaquetando la aplicaci칩n!"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo "Ejecutando pruebas!"

  qa:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: qa
      run: echo "Ejecutando an치lisis de calidad!"

  deploy:
    needs: qa
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: echo "Desplegando la aplicaci칩n!"
